### ISSUE TITLE
MotionLayout 怎么防止快速点击

### ISSUE THREAD

**Issue by LatlngV** [wkk-knight/knight_blog_demo#1]

**Comment by knight-kk** [comment]
你是不是想动画在执行的过程中，再次点击不让动画它重头开始？
那就xml 方式就不行了，可以使用代码处理

1. 把xml中的`<OnClick/>` 去掉
2. 自己编写对应的点击事件来控制动画

处理代码如下

```kotlin
        binding.root.setOnClickListener {
            //运动中currentState的值是-1 不做处理
            if (binding.motionLayout.currentState == -1) {
                return@setOnClickListener
            }

            if (binding.motionLayout.currentState == binding.motionLayout.startState) {
                binding.motionLayout.transitionToEnd()
            } else if (binding.motionLayout.currentState == binding.motionLayout.endState) {
                binding.motionLayout.transitionToStart()
            }
        }
```

**Comment by LatlngV** [comment]
多谢大佬指教，可以了













在 2020-11-30 14:50:10，"wkk-knight" <notifications@github.com> 写道：

你是不是想动画在执行的过程中，再次点击不让动画它重头开始？
那就xml 方式就不行了，可以使用代码处理

把xml中的<OnClick/> 去掉
自己编写对应的点击事件来控制动画

处理代码如下

        binding.root.setOnClickListener {

            //运动中currentState的值是-1 不做处理if (binding.motionLayout.currentState ==-1) {

                return@setOnClickListener

            }



            if (binding.motionLayout.currentState == binding.motionLayout.startState) {

                binding.motionLayout.transitionToEnd()

            } elseif (binding.motionLayout.currentState == binding.motionLayout.endState) {

                binding.motionLayout.transitionToStart()

            }

        }
